export const INPUTS = {
  TOKEN: 'github-token',
  TEST_SCRIPT: 'test-script',
  MIN_THRESHOLD: 'min-threshold',
};

export const commentVariable = {
  title: '{{title}}',
  total: '{{total}}',
  coverage: '{{coverage}}',
  summary: '{{summary}}',
  details: '{{details}}',
  failed: '{{failed}}',
  threshold: '{{threshold}}',
};

export const commentTag = '<!-- @abolkog/jest-pr-code-coverage-action -->';

export const FILE_EXTENSIONS = ['js', 'ts', 'jsx', 'tsx'];

export const ANSI_REGX = /[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g;

export const COMMENTS_TEMPLATE = {
  base: `
## {{title}} :open_umbrella:

### Total Coverage in this PR: {{total}}

{{threshold}}

{{summary}}

{{coverage}}

{{failed}}

<p align="right">Generated by <a href="https://github.com/abolkog/jest-pr-code-coverage">Jest PR Code Coverage action</a>

${commentTag}
  `,
  coverage: `
<hr />

<details>
<summary>Coverage report</summary>

{{details}}

</details>
  `,
  error: `
### Failed Tests: {{total}}

<hr />

<details>

{{details}}

</details>
  `,
};
